title: QuangN
author: Quang Nguyen
description: Computer Scientist (Artificial Intelligence)

markdown: kramdown
highlighter: null
permalink: /:title

url: http://www.quangn.com
baseurl:

redcarpet:
  extensions: [strikethrough, tables]

sass:
  sass_dir: public/css
  style: :compressed

gems:
  - jekyll-sitemap
